source      : ./dev
destination : ./dev/_statics
exclude     : [ 'assets', 'icons', 'mock', 'scripts', 'stylesheets' ]
name        : Jekyll Starter
author      : Paulo Campos
baseUrl     : https://paulo-campos.github.io/portfolio
permalink   : /:title.html
